app = "pinterest-downloader-bot"
primary_region = "sin"  # Singapore region, you can change this

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source = "pinterest_data"
  destination = "/data"

# Deploy Specific Environment Variables
[deploy]
  release_command = "python -m pip install -r requirements.txt"

[processes]
  app = "python main.py"
