# Fly.io Configuration for PintrestDownloadsBot
app = "PintrestDownloadsBot"  # Application name
primary_region = "iad"  # Set this to your preferred region (e.g., iad, fra, etc.)

[build]
  builder = "paketo-buildpacks/builder:base"  # Python-compatible builder

[deploy]
  release_command = "python3 main.py"  # Ensure this matches your bot's main script
